[package]
name = "uisce"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.8.2"
csv = "1.1"
actix-web = "4"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
